version: '3'

services:
  server_app:
    build: .
    ports:
      - "8000:8000"
    image: app:server
    container_name: server
    command: gunicorn main:app --host 0.0.0.0 --port 8000
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - server_app
    image: app:nginx
    container_name: nginx
  